In [2]:
import torch
import torch.nn as nn

In [6]:
inputs=torch.tensor([3.0,2.0,-1.0])

In [10]:
neuron=nn.Linear(in_features=3,out_features=1) #creating a neuron
output=neuron(inputs)

In [12]:
print(output)

tensor([0.8163], grad_fn=<AddBackward0>)


In [14]:
neuron.weight


Parameter containing:
tensor([[ 0.4158, -0.2041, -0.0247]], requires_grad=True)

In [16]:
neuron.bias

Parameter containing:
tensor([-0.0475], requires_grad=True)

In [18]:
neuron.weight@inputs.T + neuron.bias  #gives same anwser as in above cell 

tensor([0.8163], grad_fn=<AddBackward0>)